<?php 
$capitulo = ""; 
$titulo = "Apresentação"; 
$abertura = "(img/abertura-global.png)";
include("components/page-header.php");
?>

<p>O Planejamento Estratégico da Superintendência de Educação a Distância (SEAD) - 2021-2030, órgão da Universidade Federal do Espírito Santo, prospecta e permite uma visão integral da unidade, define objetivos, indicadores, metas gerais e abrangentes e visa, sobretudo, reduzir as incertezas com as quais iremos lidar neste momento de grandes mutações do ambiente no qual estamos inserido. O planejamento é composto pelo diagnóstico (levantamento e análise da situação atual e as tendências das principais variáveis ambientais); direção estratégica (diretriz a ser adotada pela SEAD com base nos aspectos ambientais externos e internos); segmentação estratégica (identificação dos mercados e das áreas de atuação em que a SEAD pretende atuar e as posturas e ênfases a serem praticadas); e as orientações estratégicas (declaração dos balizadores de atuação do órgão, coerente com a direção e a segmentação estratégicas).</p>

<p>O processo de planejamento da estratégia foi desenvolvido de forma atípica, em virtude do necessário distanciamento social imposto pela pandemia de Covid-19, doença causada pelo corona vírus (Sars-Cov-2). Apesar das dificuldades enfrentadas em decorrência da situação, o resultado final deste trabalho sintetiza aonde queremos chegar, em que lapso de tempo e como faremos para atingir os objetivos propostos. Entendemos que a disciplina de pensar e gerenciar um órgão como a SEAD, no contexto da sociedade global-digital, é totalmente diferente. Por isso, consideramos fundamental definir a estratégia a ser adotada com vistas ao direcionamento de sua condução. Paralelamente, precisamos desenvolver três importantes fatores. Primeiro, devemos nos orientar por conceitos inovadores, isto é, desenvolvermos ideias e mobilizarmos a criatividade internamente. Segundo, devemos ser competentes organizacionalmente e, para que isso ocorra, devemos fixar padrões de desempenho para todos os nossos colaboradores. Por último, devemos acompanhar o avanço tecnológico – outro grande acelerador de mudanças que condiciona o desenvolvimento da estratégia das organizações.</p>

<p>Este planejamento detalha os objetivos institucionais relacionados à SEAD, inseridos no inseridos no <a href="https://avaliacaoinstitucional.ufes.br/sites/avaliacaoinstitucional.ufes.br/files/field/anexo/PPI-UFES.pdf">Plano Pedagógico Institucional (PPI)</a> e no <a href=https://proplan.ufes.br/sites/proplan.ufes.br/files/field/anexo/pdi_2021-2030.pdf>Plano de Desenvolvimento Institucional – UFES (PDI 2021-2030)</a>, que deverão ser implementados através de projetos estratégicos relacionados, entre outros, aos seguintes tópicos: ampliação da oferta de
vagas em cursos, na modalidade EAD, de graduação, pós-graduação, extensão e livres; institucionalização e estabelecimento de bases legais para implantar o Ensino Híbrido (<a href=https://www.in.gov.br/materia/-/asset_publisher/Kujrw0TZC2Mb/content/id/57496468/do1-2018-12-31-portaria-n-1-428-de-28-de-dezembro-de-2018-57496251>Portaria MEC/GM Nº 1.428/2018</a>); implantação e operacionalização da parceria UFES/UNA-SUS (credenciamento de 29/04/2014); redução dos índices de retenção e evasão nos cursos de graduação; melhoria dos conceitos dos cursos de graduação e pós-graduação; viabilização de infraestrutura predial para o funcionamento da SEAD; e a viabilização do financiamento da EAD
de forma simétrica ao fomento da educação presencial.</p>

<p>Para elaboração deste documento, realizamos análises externas e internas (macro e microambiente), identificando oportunidades e ameaças, forças e fraquezas, tendências, temas emergentes, perspectivas e incertezas que podem impactar o ambiente educacional e influenciar na dinâmica de funcionamento deste órgão como, por exemplo, a publicação da <a href=https://www.in.gov.br/en/web/dou/-/portaria-n-2.117-de-6-de-dezembro-de-2019-232670913>Portaria nº 2.117/2019</a>, do Ministério da Educação, que dispõe sobre a oferta de carga horária na modalidade de Ensino a Distância - EAD em cursos de graduação presenciais ofertados por
Instituições de Educação Superior - IES pertencentes ao Sistema Federal de Ensino (até o limite de 40% da carga horária total do curso, exceto Medicina), ou mais recentemente, a publicação da <a href=https://www.in.gov.br/en/web/dou/-/portaria-n-433-de-22-de-outubro-de-2020-284699498>Portaria MEC 433/2020</a>, que instituiu o Comitê de Orientação Estratégica - COE para a elaboração de iniciativas de promoção à expansão da educação superior por meio digital em Universidades Federais, no âmbito da Secretaria de Educação Superior/MEC, associada à <a href=https://www.in.gov.br/en/web/dou/-/portaria-n-434-de-22-de-outubro-de-2020-284699573>Portaria MEC 434/2020</a>, que instituiu um Grupo de Trabalho com a finalidade de subsidiar a discussão, a elaboração e a apresentação de estratégias para a ampliação da oferta dos cursos de nível superior, na modalidade de educação à distância - EAD, nas universidades federais. E neste complexo contexto não podemos esquecer que a ocorrência da pandemia causada pelo novo corona vírus (Sars-Cov-2) provocará mudanças no sistema educacional brasileiro na era pós-pandemia, segundo análise de diversos especialistas. </p>

<p>Identificamos, também, algumas contingências e desafios a serem superados, tais como: a mudança de mentalidade (aprende-se a todo o momento e em todo lugar, de modos diferentes e com recursos diferentes); acesso aos novos meios digitais (grande parte da população não tem acesso aos meios digitais ou à internet); falta de investimento em pesquisas (faltam pesquisas interdisciplinares em todo o mundo, não apenas no Brasil, quanto à expansão das práticas educativas aplicadas aos novos meios e ao avanço dos recursos tecnológicos);
capacitação profissional (lidamos com profissionais – professores, tutores, educadores, etc. – oriundos de um sistema de ensino tradicional, que são consumidores de novas tecnologias e lidam com as novas linguagens, ou seja, uma geração de profissionais que vive plenamente essa transição); e melhorias quanto à qualidade (da mesma forma que
no ensino presencial, há instituições qualificadas e não qualificadas entre as instituições de ensino a distância. Tanto o ensino presencial tradicional quanto os cursos à distância devem ter a qualidade de seus processos como uma prioridade, reavaliando-se e reinventando-se constantemente). </p>

<p>Com base nos insumos referentes à avaliação de estratégias, no diagnóstico do ambiente externo e interno, considerando as oportunidades e ameaças, conhecendo nossos pontos fortes e fraquezas, definimos os objetivos e indicadores estratégicos do órgão, para o ciclo estratégico 2021-2030, que irão impactar diretamente os resultados que serão obtidos pela SEAD/UFES. Também estabelecemos as prioridades que serão trabalhadas no órgão: planejamento e avaliação institucional; prospecção, desenvolvimento e oferta de novos cursos; organização administrativa; gestão de pessoas; gestão orçamentária; tecnologia da informação; infraestrutura; gestão ambiental; comunicação; acessibilidade; inovação, empreendedorismo e transferência de tecnologias; governança, controle interno e gestão de riscos. </p>

<p>Motiva-nos fortemente a crença de que a educação a distância no Brasil é uma realidade incontestável e irreversível. O país segue um movimento mundial de alteração da primazia da sala de aula em formato tradicional, centrada em estudantes que assistem ao protagonismo docente em frente a uma lousa. As metodologias de ensino ativas e fundamentadas em projetos migram para o centro de todo o processo de ensino-aprendizagem, dando protagonismo ao estudante para explorar não apenas outros espaços e momentos, mas o meio digital e
seus inovadores recursos. Apesar das críticas frequentes e dos obstáculos que enfrentamos e enfrentaremos, acreditamos fortemente que várias práticas de ensino serão executadas, em um futuro próximo, cada vez mais a distância. É como afirma Jocquinot (1993), a distância só pode ser compreendida, e mesmo vencida, quando se estabelece os modos de diálogo, comunicação e acesso, quando se interliga os pontos apartados e os une reduzindo as ausências.</p>

<?php include('components/page-footer.php'); ?>