<?php 
$capitulo = "Capítulo 1";
$titulo = "Introdução";
$abertura = "(img/abertura-capX.png)";
include("components/page-header.php"); 
?>

<p>Primeiramente, faz-se necessário esclarecer o uso de alguns termos que aparecerão ao longo do texto. A falta de consenso sobre as designações para o vocábulo “<em lang="en">game</em>” no Brasil, até mesmo em dissertações, teses e principais publicações da área é criticada por Domingues (2011, p. 40). O autor aponta as denominações mais frequentes: “<em lang="en">game</em>”, “<em lang="en">videogame</em>”, “jogo eletrônico” e “jogo digital”.</p>
<p>Este livro adota o termo “jogo digital<em>”</em>, a partir da nomenclatura dos cursos de formação no país cadastrados atualmente no sistema e-MEC<a class="nota" href="#nota1" id="ref1" title="Sistema e-MEC: Disponível em: http://emec.mec.gov.br/ Acesso em: ago. 2020.">1</a>, tanto de grau bacharelado, como tecnólogo. Em alguns momentos, será usada a expressão “solução de design que envolve jogos digitais ou seus elementos” para se referir tanto ao processo de design educacional que envolve analisar, planejar, implementar e avaliar o uso de soluções já desenvolvidas (jogos educacionais, jogos comerciais, metaversos<a class="nota" href="#nota2" id="ref2" title="Metaverso ou mundo virtual é um espaço digital criado a partir de Computação Gráfica, com o qual é possível interagir via dispositivos de entrada e de saída (NETTO; MACHADO; OLIVEIRA, 2002, p. 5).
">2</a> e gamificação<a class="nota" href="#nota3" id="ref3" title="Kapp, Blair e Mesch (2014, p. 54) definem gamificação como o uso de elementos de jogo para engajar pessoas, motivar ações, promover aprendizagem e resolver problemas.">3</a>), quanto ao processo de design, enquanto compreensão, estruturação, produção, aplicação e avaliação de novas soluções.</p>
<p>O contexto da pesquisa é a Educação a Distância que, de acordo com o Art.1º do Decreto 9.057, de 25 de maio de 2017, é uma modalidade educacional que tem como essenciais os meios e as tecnologias de informação e comunicação, a qualificação e as políticas de acesso para o desenvolvimento, o acompanhamento e avaliação de atividades educacionais, em que o processo de mediação didático-pedagógica conta com sujeitos em lugares e tempos diversos.</p>
<p>Embora os autores da literatura consultada não arrisquem citar ou datar a primeira solução que envolva jogos digitais ou seus elementos a ser usada na Educação em qualquer modalidade, é possível encontrar diversos estudos que exaltam seu sucesso nessa tarefa.</p>
<p>Em âmbito nacional, o aumento da utilização de jogos na Educação a Distância é evidenciado pelo Relatório Analítico de Aprendizagem a Distância no Brasil, realizado pela Associação Brasileira de Educação a Distância (ABED), divulgado junto aos censos EAD Brasil<a class="nota" href="#nota4" id="ref4" title="Disponível em: http://www.abed.org.br/site/pt/midiateca/censo_ead/. Acesso em ago. 2020.">4</a> entre 2009 e 2019<a class="nota" href="#nota5" id="ref5" title="Até o momento de encerramento desta pesquisa, o último censo publicado pela ABED que contou com dados sobre o uso de jogos na EAD foi o de 2018, divulgado no segundo semestre de 2019.">5</a>, e pelo Regional Report (Freeman, Adams Becker e Hall, 2015), organizado pela comunidade internacional de tecnologia educacional New Media Consortium (NMC), divulgado em 2015. No cenário internacional, os relatórios Horizon Report<a class="nota" href="#nota6" id="ref6" title="Horizon Report. Disponível em: https://library.educause.edu. Acesso em ago. 2020.">6</a>, organizados pela NMC e divulgados entre 2005 e 2020 atestam que os jogos digitais e a gamificação ganharam espaço na Educação Superior.</p>
<p>Apesar dessas constatações que expressam o aumento do uso de jogos na Educação e na Educação a Distância, a pesquisa bibliográfica realizada demonstra que ainda são poucos os estudos científicos que tratam do tema envolvendo os principais agentes: professores, estudantes e designers. </p>
<p>A literatura consultada cita situações nas quais o professor ou o estudante pode ser o criador de seu próprio jogo, mas ambas as situações levam à necessidade de professores com conhecimento em Design de Jogos. Destaca-se que, apesar de tal constatação frequente na literatura consistir em uma realidade, esta, entretanto, não exclui a possível atuação e participação do designer nesse processo, no auxílio ao desenvolvimento, ou mesmo na prestação de consultoria e treinamento.</p>
<p>Além disso, ao discorrer sobre o desenvolvimento e o uso de soluções de jogos digitais ou seus elementos em cursos de graduação (bacharelado, licenciatura e tecnólogo) e de pós-graduação (<em>lato</em> e <em>stricto sensu</em>), contribui-se com a Educação no nível Superior e também em outros níveis, pois tal ação implica em fazer reflexões que podem estimular o desenvolvimento e uso de jogos por futuros educadores e educandos.</p>
<p>Desse modo, o problema apresentado ao longo desta obra tem relação com a atuação de designers, professores e estudantes no processo de design de soluções que envolvem jogos digitais ou seus elementos para a Educação a Distância. Destarte, parte-se da hipótese de que esses agentes têm participação limitada no processo de design dessas soluções e que é necessário um modelo para ampliar sua atuação. Logo, o objetivo é a criação de um modelo para ampliar a participação de designers, professores e estudantes.</p>
<p>Para tanto, o estudo conta com pesquisa bibliográfica e revisão de literatura<a class="nota" href="#nota7" id="ref7" title="O detalhamento da pesquisa bibliográfica nas obras consultadas e os critérios de seleção e exclusão da revisão de literatura estão explicitados em cada capítulo.">7</a> para levantar e discutir as soluções de design que envolvem jogos digitais ou seus elementos para a Educação Superior a Distância, os modelos de design e a atuação dos agentes no processo projetual, pois estes traçam e constroem um panorama preliminar do objeto de estudo. </p>
<p>A averiguação das abordagens e particularidades das soluções encontradas na literatura estão organizadas segundo o método misto<a class="nota" href="#nota8" id="ref8" title="O método misto, segundo Creswell (2007, p. 211) emprega a coleta e análise de dados de modo qualitativo e quantitativo.">8</a> e o método comparativo<a class="nota" href="#nota9" id="ref9" title="O método comparativo, segundo Marconi e Lakatos (2010, p. 107), se ocupa da explicação dos fenômenos e permite analisar um dado concreto, com a finalidade de verificar similitudes e explicar divergências.">9</a> e engendra subsídios para a criação de um modelo para ampliar a inserção de designers, estudantes e professores no processo de design, de modo a permitir reflexão e corroborar suas participações na feitura das soluções.</p>
<p>Esta obra está organizada em capítulos. O capítulo intitulado “Design, Jogo e Aprendizagem” aborda o Design de Jogos, a Aprendizagem Baseada em Jogos Digitais e a gamificação na Educação, com a comparação de seus métodos de design e a discussão do papel do designer.  </p>
<p>O capítulo seguinte, “Educação a Distância”, diz respeito às características dessa modalidade educacional, as teorias de aprendizagem mais relatadas na literatura consultada e a comparação das abordagens para o design de recursos educacionais e reflexões sobre a atuação do designer nesse contexto.</p>
<p>A revisão narrativa apresentada nesses capítulos tem como resultado a geração de um instrumento de coleta de dados<a class="nota" href="#nota10" id="ref10" title="Apêndice A.">10</a>, utilizado para a realização da revisão sistemática de literatura, organizada no capítulo subsequente, intitulado “O lugar do jogo na Educação a Distância”, que relata as soluções que envolvem jogos digitais ou seus elementos no contexto nacional e internacional, bem como os elementos principais observados e a participação de professores, designers e estudantes nos estudos relatados.</p>
<p>O quinto capítulo apresenta o “Modelo de design colaborativo de soluções que envolvem jogos digitais ou seus elementos para a Educação a Distância”, com o intuito de ampliar a participação dos agentes no processo de design. São detalhadas as etapas, as diretrizes e explicados detidamente os elementos e os instrumentos para avaliação projetual e de design colaborativo do modelo proposto.</p>
<p>A motivação para desenvolver a pesquisa surgiu a partir de inquietações durante a trajetória da pesquisadora, que possui experiência na coordenação e participação no desenvolvimento de jogos digitais e soluções lúdicas que contemplem seus elementos e princípios, voltados para a Educação Superior a Distância, no Laboratório de Design Instrucional (LDI) da Universidade Federal do Espírito Santo (Ufes); experiência docente, tendo ministrado as disciplinas “Estudo e Concepção de Jogos” e “Jogos Educativos” para o Departamento de Desenho Industrial e curso de Design da instituição supracitada; e experiência como pesquisadora e extensionista na área de jogos digitais e jogos de mesa para a educação presencial em outros níveis. </p>
<p>Essas circunstâncias se mostraram propícias à realização de um estudo para investigar aspectos de uma subárea do Design, relacionando-a a outro campo do saber, ao considerar soluções de design que envolvem jogos digitais ou seus elementos para a Educação a Distância e a atuação de professores, estudantes e designers no processo de design, a fim de gerar uma contribuição para a ampliar a atuação dos agentes e, consequentemente, corroborar a estruturação de um design lúdico na conjectura dessa modalidade educacional. </p>


<div id="notas">
  <dl>
    <dt id="nota1">1</dt>
    <dd>Sistema e-MEC: Disponível em: <a href="http://emec.mec.gov.br/">http://emec.mec.gov.br/</a>. Acesso em: ago. 2020. <a href="#ref1" class="retornar">Ver no texto</a></dd>
    <dt id="nota2">2</dt>
    <dd>Metaverso ou mundo virtual é um espaço digital criado a partir de Computação Gráfica, com o qual é possível interagir via dispositivos de entrada e de saída (NETTO; MACHADO; OLIVEIRA, 2002, p. 5). <a href="#ref2" class="retornar">Ver no texto</a></dd>
    <dt id="nota3">3</dt>
    <dd>Kapp, Blair e Mesch (2014, p. 54) definem gamificação como o uso de elementos de jogo para engajar pessoas, motivar ações, promover aprendizagem e resolver problemas. <a href="#ref3" class="retornar">Ver no texto</a></dd>
    <dt id="nota4">4</dt>
    <dd>Disponível em: <a href="http://www.abed.org.br/site/pt/midiateca/censo_ead/">http://www.abed.org.br/site/pt/midiateca/censo_ead/</a>. Acesso em ago. 2020. <a href="#ref4" class="retornar">Ver no texto</a></dd>
    <dt id="nota5">5</dt>
    <dd>Até o momento de encerramento desta pesquisa, o último censo publicado pela ABED que contou com dados sobre o uso de jogos na EAD foi o de 2018, divulgado no segundo semestre de 2019. <a href="#ref5" class="retornar">Ver no texto</a></dd>
    <dt id="nota6">6</dt>
    <dd>Horizon Report. Disponível em: <a href="https://library.educause.edu">https://library.educause.edu</a>. Acesso em ago. 2020. <a href="#ref6" class="retornar">Ver no texto</a></dd>
    <dt id="nota7">7</dt>
    <dd>O detalhamento da pesquisa bibliográfica nas obras consultadas e os critérios de seleção e exclusão da revisão de literatura estão explicitados em cada capítulo. <a href="#ref7" class="retornar">Ver no texto</a></dd>
    <dt id="nota8">8</dt>
    <dd>O método misto, segundo Creswell (2007, p. 211) emprega a coleta e análise de dados de modo qualitativo e quantitativo. <a href="#ref8" class="retornar">Ver no texto</a></dd>
    <dt id="nota9">9</dt>
    <dd>O método comparativo, segundo Marconi e Lakatos (2010, p. 107), se ocupa da explicação dos fenômenos e permite analisar um dado concreto, com a finalidade de verificar similitudes e explicar divergências. <a href="#ref9" class="retornar">Ver no texto</a></dd>
    <dt id="nota10">10</dt>
    <dd>Apêndice A. <a href="#ref10" class="retornar">Ver no texto</a></dd>
  </dl>
</div>

<?php include('components/page-footer.php'); ?>