<?php 
$capitulo = ""; 
$titulo = "Conclusão"; 
$abertura = "(img/abertura-global.png)";
include("components/page-header.php"); 
?>

<p>A motivação para esta pesquisa surgiu a partir da inquietação e da vivência da pesquisadora, enquanto designer atuante na produção de soluções de design para a Educação a Distância que envolvem jogos ou seus elementos, ao se deparar com limitações na atuação de designers, professores e estudantes no processo projetual. Nesse sentido, o perfil da autora, que apresenta formação e atuação na área do Design, somado à experiência como jogadora/usuária, docente e coordenadora de projetos de jogos digitais para a Educação a Distância, por meio do Laboratório de Design Instrucional da Universidade Federal do Espírito Santo (LDI-Ufes<a class="nota" href="#nota1" id="ref1" title="Laboratório de Design Instrucional. http://ldi.ufes.br/. Acesso em: abr. 2020.">1</a>), contribuiu para o desenvolvimento da pesquisa e do modelo.</p>
<p>A partir da investigação das abordagens projetuais de Design de Jogos, de Aprendizagem Baseada em Jogos Digitais e de gamificação, identificou-se que os modelos apresentam diferentes concentrações de esforços durante as etapas. Enquanto o Design de Jogos aloca maiores esforços nas etapas de concepção, estruturação e prototipagem com testes, os modelos para desenvolvimento de jogos educacionais enfocam fases de estruturação, distribuição e avaliação do projeto, e os modelos de gamificação apresentam maior peso na etapa de estruturação.</p>
<p>A compreensão do contexto da Educação a Distância, suas particularidades em relação ao uso da tecnologia e as abordagens pedagógicas e projetuais contribuíram, juntamente com a pesquisa realizada sobre a área Design de Jogos, para aprofundar e definir parâmetros para o levantamento de dados sobre as produções nacionais e internacionais. </p>
<p>A averiguação da atuação do designer de jogos em contextos de entretenimento e educacional – de jogos, simulações ou de gamificação – revelou que esse é o profissional que atua em equipe, como defensor de uma experiência de jogo que estimule o jogador e transforme suas falhas em motivação para superar e atingir metas.</p>
<p>A atuação do designer foi assinalada com menos prescrições no âmbito da Educação a Distância. Trata-se de um profissional que pode atuar de modo mais intenso nas etapas de compreensão e estruturação, mas que também pode atuar nas demais fases, sobretudo no acompanhamento da implementação e na avaliação da proposta. É relevante ressaltar que houve disparidade entre as definições dos autores e há dois tipos principais de designers que atuam na Educação a Distância – o designer educacional (CBO<a class="nota" href="#nota2" id="ref2" title="CBO – Classificação Brasileira de Ocupações, segundo o Ministério do Trabalho. Disponível em: http://www.mtecbo.gov.br. Acesso em abr. 2020.">2</a> 2394-35), e o designer gráfico (CBO 2624-10). </p>
<p>A identificação e comparação das etapas das abordagens projetuais da subárea Design de Jogos e do contexto da Educação a Distância permitiram estruturar o entendimento de como se dá a atuação dos agentes no processo de design, ao longo da coleta de dados e averiguação das experiências nacionais e internacionais. Por meio da ficha de categorização desenvolvida e utilizada, os dados organizados destas experiências revelaram um diversificado panorama em quesitos de soluções, tais como o tipo de proposta, o gênero do jogo, os tipos e elementos das soluções de gamificação, característica da linguagem gráfica, a tecnologia utilizada para produção, implementação e uso, os recursos para o projeto, as características das equipes desenvolvedoras, o tempo de desenvolvimento, o método de desenvolvimento, a avaliação e os recursos. Também foram verificados quesitos e aspectos pedagógicos, considerando as abordagens em relação ao tema, as características de uso, incluindo a interação entre os sujeitos, o tempo de uso, além da autoria e a abertura da proposta.</p>
<p>As dificuldades encontradas ao longo da realização da pesquisa bibliográfica, sobretudo para a sistematização e verificação dos resultados do panorama nacional e internacional, estão relacionadas à quantidade e heterogeneidade da amostra, principalmente quanto à falta de uniformidade das informações sobre desenvolvedores, percurso, solução projetual, verificação e mensuração dos resultados dos estudos. Nesse ensejo, contudo, os métodos utilizados para abordar os dados qualitativamente e, posteriormente, cotejá-los segundo aspectos quantitativos, se mostraram adequados para a compreensão do cenário.</p>
<p>A partir da análise dos dados dos estudos, percebeu-se que a atuação do designer nas experiências que envolvem jogos apresentou concentração maior nas etapas de compreensão, estruturação e produção; enquanto o estudante teve maior participação nas etapas finais, de aplicação e avaliação; e o professor, por sua vez, teve maior participação nas etapas compreensão, aplicação e avaliação. Já nas experiências de gamificação, observou-se redução na participação do estudante em todo o processo, com exceção da etapa de aplicação; o designer teve participação menor na avaliação; e o professor participou de modo constante nas etapas iniciais e, de modo mais intenso, na etapa de aplicação.</p>
<p>Desse modo, os resultados obtidos a partir do método comparativo permitiram confirmar que designers, professores e estudantes atuam de modo limitado no processo de design de soluções que envolvem jogos digitais ou seus elementos, sendo necessária a proposta de um modelo para expandir suas participações.</p>
<p>A partir desses resultados, o estudo voltou o foco à elaboração de um modelo para a ampliação da atuação dos agentes no processo de design. O <em>framework </em>proposto foi construído a partir das averiguações na revisão sistemática de literatura e é composto por instrumentos que propiciam o design e a colaboração, com a apresentação de listas de verificação, diretrizes, e modelos para avaliação projetual e de design colaborativo de todas as etapas.</p>
<p>A sistematização e o cotejo das etapas do modelo proposto com as fases dos modelos de Design de Jogos, Aprendizagem Baseada em Jogos Digitais, gamificação na Educação e modelos de design de recursos educacionais permitem afirmar que o <em>framework</em> apresentado é abrangente em relação aos demais, por considerar cinco dimensões projetuais (controle de projeto, interação e comunicação, coleta de dados, aspectos pedagógicos e aspectos projetuais) que abarcam características dos demais métodos ao longo das etapas do processo.</p>
<p>Além disso, o <em>framework</em> desenvolvido propõe: </p>
<ol type="a">
<li>O design colaborativo entre professores, estudantes e designers, com a presença de sugestões para o codesign (os usuários serem criadores ou cocriadores com a assistência e mediação do designer no processo projetual); e de design participativo (os usuários participam e contribuem para o desenvolvimento da solução junto ao designer); </li>
<li>Gerar soluções diversas, tais como jogo e gamificação, em razão da participação dos usuários e a decisão pelo tipo de solução fazer parte do processo projetual ao longo das etapas iniciais, além de abordar decisões de desdobramentos (a escolha do tipo ou do gênero, dos elementos, do método para o desenvolvimento, da abordagem do tema); </li>
<li> Gerar recursos abertos e reutilizáveis, estimulando o redesign e a modificação do projeto para usos futuros em outros cursos ou disciplinas, visto que a abertura do recurso e a discussão do uso posterior são pontos discutidos; </li>
<li>A autoavaliação de projetos para retroalimentar o processo, com o uso dos modelos de avaliação projetual e de design colaborativo, e por fases da etapa de avaliação (como, por exemplo, a avaliação dos resultados do projeto e da produção de um registro de <em>post mortem</em>).</li>
</ol>
<p>Como resultados e contribuições da pesquisa, pode-se pontuar:</p>
<ol type="a">
<li>O apontamento de especificidades e comparações entre etapas de diversos modelos de Design de Jogos, Aprendizagem Baseada em Jogos Digitais, gamificação na Educação e modelos de design de recursos educacionais, com a discussão acerca da atuação do designer nesses processos;</li>
<li>A classificação e apresentação dos resultados da revisão de literatura como contribuição para o estado da arte acerca do design de soluções que envolvem jogos digitais ou seus elementos para a Educação Superior a Distância;</li>
<li>A apresentação de um <em>framework</em> que estimula ampliar a participação de designers, professores e estudantes no processo de design de soluções que envolvem jogos digitais ou seus elementos para a modalidade a distância; com um conjunto de instrumentos (questões para os agentes, <em>checklists</em>, diretrizes e  modelos de avaliação projetual e de design colaborativo), de modo a servir de orientação para trabalhos futuros que tenham como objetivo promover o design colaborativo e ampliar a participação desses agentes.</li>
</ol>
<p>Por fim, é importante ressaltar que o Design de Jogos é uma subárea de atuação recente no país. É preciso questionar qual a inserção, o envolvimento e a valorização do profissional designer de jogos no contexto educacional e, ainda, como é a formação desse profissional durante sua graduação para atuar em tal cenário. Do mesmo modo, é fundamental investigar como as instituições fornecem condições estruturais e de formação para que professores e estudantes projetem e produzam soluções.</p>
<p>Em vistas disso, espera-se que os resultados desta obra contribuam para o desenvolvimento de novas pesquisas acerca da atuação de designers em contexto educacional e para a facilitação da atuação colaborativa entre professores, estudantes e designers na produção de soluções de design que envolvem jogos digitais ou seus elementos para a Educação a Distância.</p>

<div id="notas">
 <dl>
   <dt id="nota1">1</dt><dd>Laboratório de Design Instrucional. <a href="http://ldi.ufes.br/">http://ldi.ufes.br/</a>. Acesso em: abr. 2020. <a href="#ref1" class="retornar">Ver no texto</a></dd>
   <dt id="nota2">2</dt><dd>CBO – Classificação Brasileira de Ocupações, segundo o Ministério do Trabalho. Disponível em: <a href="http://www.mtecbo.gov.br">http://www.mtecbo.gov.br</a>. Acesso em abr. 2020. <a href="#ref2" class="retornar">Ver no texto</a></dd>
 </dl>
</div>

<?php include('components/page-footer.php'); ?>